apiVersion: apps/v1
kind: Deployment
metadata:
  name: docx-to-pdf-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docx-to-pdf
  template:
    metadata:
      labels:
        app: docx-to-pdf
    spec:
      containers:
        - name: docx-to-pdf
          image: akshitgarg9115/docx-to-pdf:latest
          ports:
            - containerPort: 80
